name: build and deploy

on:
  push:
    branches: [ main ]

  #Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  reusable-build:
    name: "ğŸ› ï¸"
    uses: vishalmamidi/workflows/.github/workflows/gradle-build.yaml@main
    secrets: inherit


  reusable-deploy:
    needs:
      reusable-build
    name: "ğŸš€"
    uses: vishalmamidi/workflows/.github/workflows/aks-deploy.yaml@main
    secrets: inherit
